version: '3'
services:
  hapi:
    build: app
    container_name: "hapi"
    volumes:
      - "/usr/src/app"
    ports:
      - "5000:5000"
  db:
    build: db
    image: "mysql-hapi"
    container_name: "mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
